### PR TITLE
Fix build system

### PR DESCRIPTION
**Pull request by jspricke**
- Add jitpack.io repos.
- Simplify installation instructions.
- Remove precompiled mapsforge-map.jar.

### CODE REVIEW

**Comment by jspricke** [comment]
This is part of getting WhereYouGo into F-Droid: https://gitlab.com/fdroid/fdroiddata/merge_requests/1410

**Comment by jspricke** [comment]
I've reworked this to use jitpack.io to get artefacts.
Note that there are two forks with fixes for jitpack.io in there, which I will replace once they are accepted upstream:
- https://github.com/asamm/locus-api-android/pull/1
- https://github.com/biylda/WhereYouGo/issues/10

**Comment by jspricke** [comment]
Locus moved to Maven, once we have mapsforge-map.jar moved and this merge we can get into F-Droid!

**Comment by jspricke** [comment]
- biylda notifications@github.com [2016-11-06 12:57]:
  > Merged #9.

Awesome, thanks! Will you tag a new version as well?

Also, what about https://github.com/biylda/WhereYouGo/issues/10

**Comment by mvdan** [comment]
ping @biylda, please tag a release - otherwise we can't publish on F-Droid

**Pull request merged**
