### PR TITLE
Improve german translation

### PR DESCRIPTION
**Pull request by Lineflyer**

### CODE REVIEW

**Comment by Lineflyer** [comment]
@biylda Can you kindly take a look at this PR. It contains some corrections for german.

**Review by kurly1 — APPROVED** [review]

**Comment by Lineflyer** [comment]
@biylda This one is still open and it would be great to see this improvements in the app. Especially the `zone_state_*` strings are hardly understandable in german.

**Comment by hakuchi** [comment]
@biylda can you please merge this request, because n the latest release(0.9.3) these errors are still present.
thx

**Review by SchoolGuy — APPROVED** [review]
As a german native I say that this looks good!

**Pull request closed without merging**
